### ISSUE TITLE
Total Power Filter Upgrade

### ISSUE THREAD

**Issue by steven-murray** [edges-collab/edges-analysis#4]
The total power filter is quite specific in the way it is written, and will not apply to a general telescope (only mid-band). The algorithm of the filter is:

* Get the sum of each spectrum (for a night/day) in three different bands (low half, upper half, total) (yielding, for each band, a "total power" as a function of GHA).
* For each band, split the total power into smallish chunks of GHA (nominally 1hr bins), and for each bin, fit a low-order polynomial to the total power.
* GHA's whose total power is outside some threshold are flagged, and the previous step is repeated, until no new GHAs are flagged. This threshold is itself thresholded: if the RMS of the residuals of the fit are very large, even 1-sigma outliers are flagged. Otherwise, only 3-4-sigma outliers are flagged.

The elements of this that are not general are:

* The hard-coded numbers defining the threshold of the threshold. The reason for the thresholding of the threshold is that really crazy data might be so non-Gaussian that nothing is flagged because the RMS is so biased high. This allows the worst offenders to be taken out easily, and then relaxing the cuts as the distribution becomes more "Gaussian". The problem is, you need to know what a "bad" RMS is to begin with -- hence the hard-coded numbers. We could get around this code-wise by allowing these numbers to be passed to the function (and having a set of well-known numbers for each band).
* It's potentially slightly too specific to force the spectrum to be split into lower, upper, total -- why not in quarters? Why not arbitrary frequency sections?
* The choice of 1hr GHA bins (and/or the choice of poly order) is not generic.
* Using total power instead of mean power is probably less generic (though it largely shouldn't matter, since we're *not* filtering on the absolute total power, but its residual to a smooth interpolator over GHA).

Potential biases that could arise here:

* As with *any* filtering based on outliers, we have to realize that the extent of the distribution is in principal infinite -- any particular outlier could really just be from the distribution, just an extreme case. By flagging this, we are inherently "clipping" the distribution and adjusting its statistics (eg. while the mean of a clipped Gaussian remains the same, its variance does not).
* In this algorithm, a poor choice of the initial "threshold of the threshold" will result in bad results. It is hard to say just how sensitive it is to these choices. 
* The algorithm relies on the inherent smoothness of the expected total power as a function of GHA (at least locally). Indeed, this is fundamentally what the filter is. Nevertheless, it clearly follows that correlated total power spikes that last for a reasonably long time will bias the polynomial fit, and these spikes may not be flagged. 

Some ideas about an upgrade:

* Using the Median Absolute Deviation instead of the RMS _may_ obviate the need for a "threshold of the threshold". It is much more robust to outliers. 
* The length of the GHA window, and the polynomial order, should be parameters to be set in the analysis, rather than hardcoded.
* It is not clear to me that it would perform better (most of the potential biases remain), but we could use a sliding-window MAD instead of the polynomial fit. The choice then would be the size of the sliding window -- too small a window and the statistics are too poor, too large and real structures are washed out. In fact, it could be used *in conjunction* with a low-order poly fit. If so, the poly fit should be on a wider window than that being flagged, to avoid edge-effects. 

Finally: most of these observations are not at all reliant on the axis being GHA -- it could be frequency, or night! We could have a fairly generic (set of) filter(s) that could be applied on any axis.

**Comment by steven-murray** [comment]
@gitul I would love any comments you can offer on this!

**Comment by gitul** [comment]
In general, the improvements to the total power filter suggested by steven-murray sound good. However, we have to remember the following (maybe steven-murray already did, and is accounting for this in his suggestion, but it is not evident to me):

(1) It is my understanding that a MAD filter assumes that the data points (when perfectly calibrated, etc.) are expected to have the same intrinsic median if the noise is reduced to zero. Is this true?

(2) If (1) is true, then you can only compare data that correspond to the same (or very similar) sky, i.e., LST or GHA. This is the reason why my TP and RMS filters rely on representing the data as a function of GHA.

(3) If (1) is true, and you do not represent the data as a function of GHA, how meaningful would the MAD be? How could you apply cuts to TPs from vastly different foreground intensities and noise? 

(4) If (1) is not true, could you (steven-murray) please clarify why? 

(5) If (1) is not true, and you apply a MAD filter to TPs with a very wide distribution (due to the points coming from different GHAs), wouldn't the "filtering power" be very week? High TPs from low foreground regions, which would normally be rejected, would be compared with high TPs from high foreground regions, and would incorrectly pass the filter.

All this is to say, I don't see how you can robustly use other axes (other than GHA or equivalent) for the filter.

Thanks!

**Comment by steven-murray** [comment]
Thanks @gitul. 

I believe (1) is true. 

(2): yes, the total-power filter (as implemented) must be done as a function of GHA, because we expect different distributions for different GHA. When I suggest that we could implement such filters over an arbitrary axis, what I mean is that we could write a very generic function that just "does the filter", and use that function for filters over either GHA or frequency or night (or some combination), as appropriate for a particular kind of filter. You could imagine averaging over GHA and doing a filter over frequency (in fact, that is what my implementation of xrfi does in edges_cal). In this case, the expectation of the median is the same in each frequency bin because GHA has been marginalised. You could also imagine doing a 2D filter over GHA and freq at the same time (HERA for example does this for RFI). 

Specifically for the total power filter (where frequency is already marginalised) it really only makes sense to do the filter as a function of GHA.
