### ISSUE TITLE
In the CombineDataStep grid per day instead of grid per file

### ISSUE THREAD

**Issue by nmahesh1412** [edges-collab/edges-analysis#98]
Some files, especially in lowband2-45deg, each day's data is split into two files because an S11 measurement was made each day and the data collection was interrupted during that time. This results in at least two files for each day. 

In the combineDataStep where we grid all the days' data into a uniform GHA grid, we get multiple arrays for the same day. 

This could lead to potential issues. One of them being: the way we implement the day_rms_filter. Here we want to calculate the RMS of the entire day's averaged residuals - which will be difficult if the entire day's data is in two files ==> two arrays

**Comment by steven-murray** [comment]
Along with this it's worth realizing that we won't always have a full day for every observed 'day', due to RFI or just turning off to take S11 for a while. In principle the RMS filter should take this into account by understanding the expected noise level. In practice, it might not make much of a difference, as long as we grid into "whole days". Note that a different problem could also arise in principle: a single file could be *longer* than a day and wrap back on itself. 

It would seem that the best overall approach would be to grid on a GHA/LST grid always starting at some LST (eg. zero), and split the files wherever they need to be split. 

However, note that this will break the `day_index` ability. It's not quite clear what could be done about this, but we could figure something out.
